### PR TITLE
Fixing isssue #1

### PR DESCRIPTION
**Pull request by AhmedElbohoty**
- [ ] Included a Preview link and screenshot showing after and before the changes.
- [ ] Included a description of the change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- [Preview Link](url)

- Fixes #<Issue Number> #1

### After:

- - - - - - - - - - - -

### CODE REVIEW

**Review by jogendra — CHANGES_REQUESTED** [review]
The preview link you provided is not working, please give a working preview link.

**Comment by AhmedElbohoty** [comment]
untitled-1

**Comment by AhmedElbohoty** [comment]
This the view after removing scrolling

**Review by jogendra — APPROVED** [review]
LGTM

**Pull request merged**
